name: Deploy Frontend to VPS

# Run this workflow on a push to the 'main' branch
on:
  push:
    branches:
      - main 
      # If your branch is 'master', change 'main' to 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # (FIX 1) Load NVM (Node Version Manager) directly
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # (FIX 2) Fix Git ownership issue
            git config --global --add safe.directory /var/www/Cell-Web/Mobile-Shop-Website-Frontend

            
            cd /var/www/Cell-Web/Mobile-Shop-Website-Frontend/ && \
            git pull origin main && \
            npm install && \
            npm audit fix && \
            npm run build